/*
文件的逻辑格式如下（实际保存时只保存数值）。

model{
    xmin,xmax,ymin,ymax,zmin,zmax;
    offsetus,offsetut;
    cloudList{
        ncloud;
        cloud{"相对于本文件的路径"}
        cloud{"相对于本文件的路径"}
        ....
    }
    groundgrid{"相对于本文件的路径"}
    texture{
	photo{"相对于本文件的路径"}
	wall{"相对于本文件的路径"}
        sky{"相对于本文件的路径"}
    }
}
groundgrid单独保存为一个文件，格式如下：
    groundgrid{
        xmin,xmax,zmin,zmax;
        xstepLen,zstepLen;
        mat{
            m,n;
            groundcell{
                v{x,y,z,1}
	        u{s,t}
   	    }
	    groundcell{
	        ....
	    }
            ....
        }
    }
每个cloud单独保存为一个文件，格式如下：
    cloud{
		avrgH;
		bottomH;
		topH;
		minH;
		color;
		removed;
        xmin,xmax,zmin,zmax;
        polygenList{
            npolygen;
            polygen{
                removed;
                vlist{
					nv;
                    v{
 						isKeyPoint;
                        v{x,y,z,1}
						u{s,t}
                        uf{sf,tf}
						un{sn,tn}
					}
					v{
 						....
					}
					....     
				}
			}
			polygen{
 				....
			}
			....

        }
        polygenList{
            ....
        }
		grid{
            xmin,xmax,zmin,zmax;
			xstepLen,zstepLen;
            m_locToWorld{a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p}
			m_worldToLoc{a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p}
			mat{
				m,n;
                cell{
 	       			isNull;
                    needcut;
					v{x,y,z,1}
					u{s,t}
					vlt{x,y,z,1}
					vrt{x,y,z,1}
					vup{x,y,z,1}
                    vdn{x,y,z,1}
                    vlup{x,y,z,1}
				    vldn{x,y,z,1}
				    vrup{x,y,z,1}
					vrdn{x,y,z,1}
					ult{s,t}
					urt{s,t}
					uup{s,t}
					udn{s,t}
					ulup{s,t}
					uldn{s,t}
					urup{s,t}
					urdn{s,t} 
                    normA{x,y,z,0}
					normB{x,y,z,0}
					normC{x,y,z,0}
	 				normD{x,y,z,0}
	     			avrgnorm{x,y,z,0}  
                    polygenList{
        				npolygen
           				polygen{
							removed;
                            vlist{
								nv;
                                v{
									isKeyPoint;
                                    v{x,y,z,1}
			   						u{s,t}
                                    uf{sf,tf}
									un{sn,tn}
								}
								v{
	   								....
								}
								....     
							}
						}
					    polygen{
 						  ....
						}
						....
					}
				}
				cell{
	    		    ....
			    }
				....
            }
		}
    }

      
   */   